import json

with open('Data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_source = [
    "# 1.3.A Market Saturation Forecast (Smoothed MoM Projection with Confidence Intervals)\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "# 1. Query: Monthly Trip Counts (2021-2025)\n",
    "query_forecast = \"\"\"\n",
    "SELECT \n",
    "    date_trunc('month', pickup_datetime) as month,\n",
    "    count(*) as total_trips\n",
    "FROM fhvhv_2019_2025_cleaned\n",
    "WHERE year(pickup_datetime) BETWEEN 2021 AND 2025\n",
    "GROUP BY 1\n",
    "ORDER BY 1\n",
    "\"\"\"\n",
    "df_f = con.execute(query_forecast).df()\n",
    "\n",
    "# 2. Calculate & Smooth MoM Growth\n",
    "df_f['mom_growth_raw'] = df_f['total_trips'].pct_change() * 100\n",
    "df_f['mom_growth'] = df_f['mom_growth_raw'].rolling(window=12, min_periods=1).mean()\n",
    "df_f = df_f.dropna(subset=['mom_growth'])\n",
    "\n",
    "# 3. Linear Regression on Smoothed Growth Trend\n",
    "df_f['month_idx'] = range(len(df_f))\n",
    "X = df_f[['month_idx']]\n",
    "y = df_f['mom_growth']\n",
    "\n",
    "model = LinearRegression()\n",
    "model.fit(X, y)\n",
    "slope = model.coef_[0]\n",
    "intercept = model.intercept_\n",
    "\n",
    "# Calculate Margin of Error (95% Confidence Interval based on RMSE)\n",
    "historical_preds = model.predict(X)\n",
    "residuals = y - historical_preds\n",
    "std_error = np.std(residuals)\n",
    "margin_of_error = 1.96 * std_error\n",
    "\n",
    "# 4. Generate Monthly Future Projections\n",
    "current_idx = len(df_f)\n",
    "df_f['Type'] = 'Historical (Smoothed)'\n",
    "df_f['Growth'] = df_f['mom_growth']\n",
    "\n",
    "if slope < 0:\n",
    "    zero_growth_idx = int(-intercept / slope)\n",
    "    if zero_growth_idx > current_idx:\n",
    "        future_indices = np.arange(current_idx, zero_growth_idx + 1)\n",
    "        future_months = [df_f['month'].max() + pd.DateOffset(months=int(i - current_idx + 1)) for i in future_indices]\n",
    "        future_preds = model.predict(future_indices.reshape(-1, 1))\n",
    "        df_future = pd.DataFrame({'Month': future_months, 'Growth': future_preds})\n",
    "    else:\n",
    "        print(\"\\nInsight: The model suggests market saturation has already been reached.\")\n",
    "        df_future = pd.DataFrame(columns=['Month', 'Growth'])\n",
    "else:\n",
    "    print(\"\\nInsight: Growth is currently accelerating. No saturation point found.\")\n",
    "    future_indices = np.arange(current_idx, current_idx + 12)\n",
    "    future_months = [df_f['month'].max() + pd.DateOffset(months=int(i - current_idx + 1)) for i in future_indices]\n",
    "    future_preds = model.predict(future_indices.reshape(-1, 1))\n",
    "    df_future = pd.DataFrame({'Month': future_months, 'Growth': future_preds})\n",
    "\n",
    "# Add Confidence Bounds\n",
    "if not df_future.empty:\n",
    "    df_future['Upper_Bound'] = df_future['Growth'] + margin_of_error\n",
    "    df_future['Lower_Bound'] = df_future['Growth'] - margin_of_error\n",
    "\n",
    "# 5. Visualization using Plotly Graph Objects for Shaded Bands\n",
    "fig = go.Figure()\n",
    "\n",
    "# Historical Line\n",
    "fig.add_trace(go.Scatter(x=df_f['month'], y=df_f['Growth'], mode='lines', name='Historical', line=dict(color='#FF00BF', width=3)))\n",
    "\n",
    "if not df_future.empty:\n",
    "    # Connect the historical line to the forecast line cleanly\n",
    "    connect_x = [df_f['month'].iloc[-1], df_future['Month'].iloc[0]]\n",
    "    connect_y = [df_f['Growth'].iloc[-1], df_future['Growth'].iloc[0]]\n",
    "    fig.add_trace(go.Scatter(x=connect_x, y=connect_y, mode='lines', name='Forecast Connection', line=dict(color='white', width=3, dash='dash'), showlegend=False))\n",
    "    \n",
    "    # Forecast Main Line\n",
    "    fig.add_trace(go.Scatter(x=df_future['Month'], y=df_future['Growth'], mode='lines', name='Forecast', line=dict(color='white', width=3, dash='dash')))\n",
    "    \n",
    "    # Confidence Bounds (Shaded Area)\n",
    "    fig.add_trace(go.Scatter(\n",
    "        x=df_future['Month'].tolist() + df_future['Month'].tolist()[::-1],\n",
    "        y=df_future['Upper_Bound'].tolist() + df_future['Lower_Bound'].tolist()[::-1],\n",
    "        fill='toself',\n",
    "        fillcolor='rgba(255, 255, 255, 0.15)',\n",
    "        line=dict(color='rgba(255, 255, 255, 0)'),\n",
    "        name='95% Confidence Interval',\n",
    "        hoverinfo=\"skip\"\n",
    "    ))\n",
    "\n",
    "fig.add_hline(y=0, line_dash=\"dash\", line_color=\"red\", annotation_text=\"Zero Growth (Saturation)\")\n",
    "fig.update_layout(\n",
    "    title='Market Saturation Forecast with 95% Confidence Interval',\n",
    "    xaxis_title='Date',\n",
    "    yaxis_title='Smoothed MoM Growth (%)',\n",
    "    template='plotly_dark',\n",
    "    hovermode=\"x unified\"\n",
    ")\n",
    "fig.show()\n",
    "\n",
    "# 6. Detailed Forecast Output\n",
    "if not df_future.empty:\n",
    "    print(\"\\n--- FORECAST WITH MARGIN OF ERROR ---\")\n",
    "    display(df_future[['Month', 'Growth', 'Lower_Bound', 'Upper_Bound']].head(12).round(3))\n",
    "    saturation_point = df_future.iloc[-1]['Month']\n",
    "    print(f\"\\nInsight: Market saturation expected on {saturation_point.strftime('%B %Y')} (± {margin_of_error:.2f}% Margin of Error).\")\n"
]

for cell in nb['cells']:
    if cell['cell_type'] == 'code' and '1.3.A Market Saturation Forecast' in ''.join(cell['source']):
        cell['source'] = new_source
        break

with open('Data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
