import json

with open('Data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 1.3.C Scenario Analysis: Uber 15% Fare Increase Impact\n",
        "# Simulating market shift if Uber raises prices by 15% for profitability targets.\n",
        "\n",
        "import pandas as pd\n",
        "import plotly.express as px\n",
        "\n",
        "# 1. Define Assumptions & Baseline (Using 2025 averages)\n",
        "query_baseline = \"\"\"\n",
        "SELECT \n",
        "    CASE \n",
        "        WHEN hvfhs_license_num = 'HV0003' THEN 'Uber'\n",
        "        WHEN hvfhs_license_num = 'HV0005' THEN 'Lyft'\n",
        "        ELSE 'Others'\n",
        "    END as provider,\n",
        "    count(*) / 12.0 as avg_monthly_trips,\n",
        "    avg(base_passenger_fare) as avg_fare\n",
        "FROM fhvhv_2019_2025_cleaned\n",
        "WHERE year(pickup_datetime) = 2025\n",
        "GROUP BY 1\n",
        "\"\"\"\n",
        "df_base = con.execute(query_baseline).df()\n",
        "\n",
        "uber_base = df_base[df_base['provider'] == 'Uber'].iloc[0]\n",
        "lyft_base = df_base[df_base['provider'] == 'Lyft'].iloc[0]\n",
        "\n",
        "# Economics Assumptions\n",
        "fare_increase_pct = 0.15  # 15% fare hike\n",
        "price_elasticity = -0.85  # Inelastic: A 1% price increase leads to a 0.85% drop in demand\n",
        "substitution_to_lyft = 0.75 # Cross-elasticity: 75% of lost Uber customers switch to Lyft\n",
        "\n",
        "# 2. Calculate Scenario Impacts\n",
        "uber_trip_drop_pct = fare_increase_pct * abs(price_elasticity)\n",
        "uber_lost_trips = uber_base['avg_monthly_trips'] * uber_trip_drop_pct\n",
        "\n",
        "uber_new_trips = uber_base['avg_monthly_trips'] - uber_lost_trips\n",
        "lyft_new_trips = lyft_base['avg_monthly_trips'] + (uber_lost_trips * substitution_to_lyft)\n",
        "\n",
        "# 3. Revenue Impact\n",
        "uber_base_rev = uber_base['avg_monthly_trips'] * uber_base['avg_fare']\n",
        "uber_new_rev = uber_new_trips * (uber_base['avg_fare'] * (1 + fare_increase_pct))\n",
        "uber_rev_change = (uber_new_rev - uber_base_rev) / uber_base_rev * 100\n",
        "\n",
        "# 4. Prepare Data for Visualization\n",
        "total_base = uber_base['avg_monthly_trips'] + lyft_base['avg_monthly_trips']\n",
        "total_new = uber_new_trips + lyft_new_trips\n",
        "\n",
        "df_scenario = pd.DataFrame({\n",
        "    'Provider': ['Uber', 'Lyft', 'Uber', 'Lyft'],\n",
        "    'Scenario': ['1. Current Baseline', '1. Current Baseline', '2. Post 15% Fare Increase', '2. Post 15% Fare Increase'],\n",
        "    'Market Share (%)': [\n",
        "        uber_base['avg_monthly_trips'] / total_base * 100,\n",
        "        lyft_base['avg_monthly_trips'] / total_base * 100,\n",
        "        uber_new_trips / total_new * 100,\n",
        "        lyft_new_trips / total_new * 100\n",
        "    ]\n",
        "})\n",
        "\n",
        "# 5. Visualization\n",
        "fig = px.bar(df_scenario, x='Scenario', y='Market Share (%)', color='Provider', barmode='stack',\n",
        "             text=df_scenario['Market Share (%)'].apply(lambda x: f'{x:.1f}%'),\n",
        "             title='Market Share Shift: Impact of Uber 15% Fare Increase',\n",
        "             color_discrete_map={'Uber': 'white', 'Lyft': '#FF00BF'})\n",
        "fig.update_layout(template='plotly_dark', width=800)\n",
        "fig.show()\n",
        "\n",
        "# 6. Strategic Conclusion\n",
        "print(\"\\n--- STRATEGIC SCENARIO REPORT: UBER 15% FARE INCREASE ---\")\n",
        "print(f\"Assumptions: Price Elasticity = {price_elasticity}, Lyft Substitution Rate = {substitution_to_lyft*100}%\")\n",
        "print(f\"\\n1. Volume Impact: Uber loses ~{uber_lost_trips/1e6:.2f} Million trips/month (-{uber_trip_drop_pct*100:.1f}%).\")\n",
        "print(f\"2. Market Share: Uber's share drops from {uber_base['avg_monthly_trips']/total_base*100:.1f}% down to {uber_new_trips/total_new*100:.1f}%.\")\n",
        "print(f\"3. Competitor Gain: Lyft absorbs ~{uber_lost_trips * substitution_to_lyft / 1e6:.2f} Million trips/month.\")\n",
        "print(f\"4. Financial Trade-off: Despite losing volume, Uber's total revenue changes by {uber_rev_change:+.1f}%.\")\n",
        "\n",
        "if uber_rev_change > 0:\n",
        "    print(\"\\nCONCLUSION: SUCCESSFUL PROFIT PLAY, BUT STRATEGICALLY RISKY.\")\n",
        "    print(\"Uber achieves its shareholder profit targets (revenue increases) because ride-hailing demand is relatively inelastic.\")\n",
        "    print(\"However, they bleed significant market share to Lyft, which could hurt their long-term network dominance.\")\n",
        "else:\n",
        "    print(\"\\nCONCLUSION: FAILED STRATEGY.\")\n",
        "    print(\"The fare increase backfires. The loss in trip volume outweighs the higher price per trip, leading to lower total revenue.\")\n"
    ]
}

nb['cells'].append(new_cell)

with open('Data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
