import json

with open('Data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_source = [
    "# 1.3.A Market Saturation Forecast (Mature Market Focus: 2023-2025)\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "# 1. Query: Monthly Trip Counts (Focus on 2023-2025 for Mature Market Trend)\n",
    "query_forecast = \"\"\"\n",
    "SELECT \n",
    "    date_trunc('month', pickup_datetime) as month,\n",
    "    count(*) as total_trips\n",
    "FROM fhvhv_2019_2025_cleaned\n",
    "WHERE year(pickup_datetime) BETWEEN 2023 AND 2025\n",
    "GROUP BY 1\n",
    "ORDER BY 1\n",
    "\"\"\"\n",
    "df_f = con.execute(query_forecast).df()\n",
    "\n",
    "# 2. Calculate & Smooth MoM Growth\n",
    "df_f['mom_growth_raw'] = df_f['total_trips'].pct_change() * 100\n",
    "# 6-month rolling average for 2023-2025 focus (more sensitive to recent trends)\n",
    "df_f['mom_growth'] = df_f['mom_growth_raw'].rolling(window=6, min_periods=1).mean()\n",
    "df_f = df_f.dropna(subset=['mom_growth'])\n",
    "\n",
    "# 3. Linear Regression on Smoothed Growth Trend\n",
    "df_f['month_idx'] = range(len(df_f))\n",
    "X = df_f[['month_idx']]\n",
    "y = df_f['mom_growth']\n",
    "\n",
    "model = LinearRegression()\n",
    "model.fit(X, y)\n",
    "slope = model.coef_[0]\n",
    "intercept = model.intercept_\n",
    "\n",
    "# Calculate Margin of Error (95% CI)\n",
    "historical_preds = model.predict(X)\n",
    "residuals = y - historical_preds\n",
    "std_error = np.std(residuals)\n",
    "margin_of_error = 1.96 * std_error\n",
    "\n",
    "# 4. Generate Future Projections (Next 24 Months)\n",
    "current_idx = len(df_f)\n",
    "future_indices = np.arange(current_idx, current_idx + 24)\n",
    "future_months = [df_f['month'].max() + pd.DateOffset(months=int(i - current_idx + 1)) for i in future_indices]\n",
    "future_preds = model.predict(future_indices.reshape(-1, 1))\n",
    "\n",
    "df_future = pd.DataFrame({\n",
    "    'Month': future_months,\n",
    "    'Growth': future_preds,\n",
    "    'Upper_Bound': future_preds + margin_of_error,\n",
    "    'Lower_Bound': future_preds - margin_of_error\n",
    "})\n",
    "\n",
    "# 5. Visualization\n",
    "fig = go.Figure()\n",
    "\n",
    "# Historical Line\n",
    "fig.add_trace(go.Scatter(x=df_f['month'], y=df_f['mom_growth'], mode='lines', name='Historical (Mature)', line=dict(color='#FF00BF', width=3)))\n",
    "\n",
    "# Forecast Main Line\n",
    "fig.add_trace(go.Scatter(x=df_future['Month'], y=df_future['Growth'], mode='lines', name='Forecast', line=dict(color='white', width=3, dash='dash')))\n",
    "\n",
    "# Confidence Interval (Shaded Area)\n",
    "fig.add_trace(go.Scatter(\n",
    "    x=df_future['Month'].tolist() + df_future['Month'].tolist()[::-1],\n",
    "    y=df_future['Upper_Bound'].tolist() + df_future['Lower_Bound'].tolist()[::-1],\n",
    "    fill='toself',\n",
    "    fillcolor='rgba(255, 255, 255, 0.15)',\n",
    "    line=dict(color='rgba(255, 255, 255, 0)'),\n",
    "    name='95% Confidence Interval',\n",
    "    hoverinfo=\"skip\"\n",
    "))\n",
    "\n",
    "fig.add_hline(y=0, line_dash=\"dash\", line_color=\"red\", annotation_text=\"Zero Growth (Saturation)\")\n",
    "fig.update_layout(\n",
    "    title='Market Saturation Forecast (2023-2025 Mature Trend)',\n",
    "    xaxis_title='Date',\n",
    "    yaxis_title='Smoothed MoM Growth (%)',\n",
    "    template='plotly_dark',\n",
    "    hovermode=\"x unified\"\n",
    ")\n",
    "fig.show()\n",
    "\n",
    "# 6. Strategic Insight\n",
    "zero_crossing = df_future[df_future['Growth'] <= 0]\n",
    "if not zero_crossing.empty:\n",
    "    saturation_date = zero_crossing.iloc[0]['Month']\n",
    "    print(f\"\\n--- MATURE MARKET ANALYSIS ---\")\n",
    "    print(f\"Projected Absolute Saturation: {saturation_date.strftime('%B %Y')}\")\n",
    "    print(f\"Margin of Error: ±{margin_of_error:.2f}%\")\n",
    "else:\n",
    "    print(\"\\n--- MATURE MARKET ANALYSIS ---\")\n",
    "    print(\"The market growth is currently stable and not projected to hit 0% within the next 24 months.\")\n"
]

for cell in nb['cells']:
    if cell['cell_type'] == 'code' and '1.3.A Market Saturation Forecast' in ''.join(cell['source']):
        cell['source'] = new_source
        break

with open('Data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
