import json

with open('Data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_source = [
    "# 1.3.A Market Saturation Forecast (Smoothed MoM Projection)\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "# 1. Query: Monthly Trip Counts (2021-2025)\n",
    "query_forecast = \"\"\"\n",
    "SELECT \n",
    "    date_trunc('month', pickup_datetime) as month,\n",
    "    count(*) as total_trips\n",
    "FROM fhvhv_2019_2025_cleaned\n",
    "WHERE year(pickup_datetime) BETWEEN 2021 AND 2025\n",
    "GROUP BY 1\n",
    "ORDER BY 1\n",
    "\"\"\"\n",
    "df_f = con.execute(query_forecast).df()\n",
    "\n",
    "# 2. Calculate & Smooth MoM Growth\n",
    "# Using a 12-month rolling average to remove extreme seasonality noise\n",
    "df_f['mom_growth_raw'] = df_f['total_trips'].pct_change() * 100\n",
    "df_f['mom_growth'] = df_f['mom_growth_raw'].rolling(window=12, min_periods=1).mean()\n",
    "df_f = df_f.dropna(subset=['mom_growth'])\n",
    "\n",
    "# 3. Linear Regression on Smoothed Growth Trend\n",
    "df_f['month_idx'] = range(len(df_f))\n",
    "X = df_f[['month_idx']]\n",
    "y = df_f['mom_growth']\n",
    "\n",
    "model = LinearRegression()\n",
    "model.fit(X, y)\n",
    "slope = model.coef_[0]\n",
    "intercept = model.intercept_\n",
    "\n",
    "# 4. Generate Monthly Future Projections\n",
    "current_idx = len(df_f)\n",
    "df_f['Type'] = 'Historical (Smoothed)'\n",
    "df_f['Growth'] = df_f['mom_growth']\n",
    "\n",
    "# Safety check for zero crossing\n",
    "if slope < 0:\n",
    "    zero_growth_idx = int(-intercept / slope)\n",
    "    if zero_growth_idx > current_idx:\n",
    "        future_indices = np.arange(current_idx, zero_growth_idx + 1)\n",
    "        future_months = [df_f['month'].max() + pd.DateOffset(months=int(i - current_idx + 1)) for i in future_indices]\n",
    "        future_preds = model.predict(future_indices.reshape(-1, 1))\n",
    "\n",
    "        df_future = pd.DataFrame({\n",
    "            'Month': future_months,\n",
    "            'Growth': future_preds,\n",
    "            'Type': 'Forecast'\n",
    "        })\n",
    "        df_plot = pd.concat([df_f[['month', 'Growth', 'Type']].rename(columns={'month': 'Month'}), df_future])\n",
    "        \n",
    "        print(\"\\n--- MONTH-BY-MONTH SATURATION TIMELINE ---\")\n",
    "        display(df_future.head(12).round(3))\n",
    "        saturation_point = df_future.iloc[-1]['Month']\n",
    "        print(f\"\\nInsight: Based on the smoothed MoM trend, the market is projected to hit 'Absolute Saturation' on {saturation_point.strftime('%B %Y')}.\")\n",
    "    else:\n",
    "        print(\"\\nInsight: The model suggests market saturation has already been reached.\")\n",
    "        df_plot = df_f[['month', 'Growth', 'Type']].rename(columns={'month': 'Month'})\n",
    "else:\n",
    "    print(\"\\nInsight: Growth is currently accelerating. No saturation point found.\")\n",
    "    future_indices = np.arange(current_idx, current_idx + 12)\n",
    "    future_months = [df_f['month'].max() + pd.DateOffset(months=int(i - current_idx + 1)) for i in future_indices]\n",
    "    future_preds = model.predict(future_indices.reshape(-1, 1))\n",
    "    df_future = pd.DataFrame({'Month': future_months, 'Growth': future_preds, 'Type': 'Forecast'})\n",
    "    df_plot = pd.concat([df_f[['month', 'Growth', 'Type']].rename(columns={'month': 'Month'}), df_future])\n",
    "\n",
    "# 5. Visualization\n",
    "fig = px.line(df_plot, x='Month', y='Growth', color='Type', \n",
    "              title='Smoothed Monthly Growth Velocity & Saturation Forecast',\n",
    "              labels={'Growth': 'Smoothed MoM Growth (%)'},\n",
    "              color_discrete_map={'Historical (Smoothed)': '#FF00BF', 'Forecast': 'white'})\n",
    "\n",
    "fig.add_hline(y=0, line_dash=\"dash\", line_color=\"red\", annotation_text=\"Zero Growth (Saturation)\")\n",
    "fig.update_layout(template='plotly_dark')\n",
    "fig.show()\n"
]

for cell in nb['cells']:
    if cell['cell_type'] == 'code' and '1.3.A Market Saturation Forecast' in ''.join(cell['source']):
        cell['source'] = new_source
        break

with open('Data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
