import json

with open('Data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_source = [
    "# 1.3.B Final Model Validation (2026 Testing)\n",
    "# This cell validates our Mature Market Forecast against the test set, including the tail of 2025 for context.\n",
    "\n",
    "# 1. Query: Actual 2026 Data\n",
    "query_2026 = \"\"\"\n",
    "SELECT \n",
    "    date_trunc('month', pickup_datetime) as month,\n",
    "    count(*) as total_trips\n",
    "FROM fhvhv_2026_plus_cleaned\n",
    "WHERE year(pickup_datetime) = 2026\n",
    "GROUP BY 1\n",
    "ORDER BY 1\n",
    "\"\"\"\n",
    "df_2026 = con.execute(query_2026).df()\n",
    "\n",
    "# 2. Query: FULL 2025 Data (to ensure rolling window works and for display context)\n",
    "query_2025_full = \"\"\"\n",
    "SELECT \n",
    "    date_trunc('month', pickup_datetime) as month,\n",
    "    count(*) as total_trips\n",
    "FROM fhvhv_2019_2025_cleaned\n",
    "WHERE year(pickup_datetime) = 2025\n",
    "GROUP BY 1\n",
    "ORDER BY 1\n",
    "\"\"\"\n",
    "df_2025_full = con.execute(query_2025_full).df()\n",
    "\n",
    "# 3. Combine and Calculate Smoothed Growth\n",
    "df_val = pd.concat([df_2025_full, df_2026]).sort_values('month')\n",
    "df_val['mom_growth_raw'] = df_val['total_trips'].pct_change() * 100\n",
    "df_val['actual_smoothed_growth'] = df_val['mom_growth_raw'].rolling(window=6).mean()\n",
    "\n",
    "# 4. Filter for Display (Oct 2025 onwards) and Prediction\n",
    "display_start = '2025-10-01'\n",
    "df_display = df_val[df_val['month'] >= display_start].copy()\n",
    "\n",
    "# Calculate predicted growth for these specific months using the model from 1.3.A\n",
    "# We need to find the correct month_idx relative to the training set df_f\n",
    "historical_months = df_f['month'].tolist()\n",
    "last_train_month = historical_months[-1]\n",
    "last_train_idx = len(df_f) - 1\n",
    "\n",
    "def get_idx(m):\n",
    "    # Calculate months difference\n",
    "    return last_train_idx + (m.year - last_train_month.year) * 12 + (m.month - last_train_month.month)\n",
    "\n",
    "df_display['month_idx'] = df_display['month'].apply(get_idx)\n",
    "df_display['predicted_growth'] = model.predict(df_display[['month_idx']])\n",
    "\n",
    "# 5. Visualization\n",
    "import plotly.graph_objects as go\n",
    "fig_val = go.Figure()\n",
    "\n",
    "# Forecast Line (from model)\n",
    "fig_val.add_trace(go.Scatter(x=df_display['month'], y=df_display['predicted_growth'], \n",
    "                             mode='lines+markers', name='Predicted (Model)', line=dict(color='#FF00BF', width=3, dash='dash')))\n",
    "\n",
    "# Actual Line (Historical Context + 2026 Test Data)\n",
    "fig_val.add_trace(go.Scatter(x=df_display['month'], y=df_display['actual_smoothed_growth'], \n",
    "                             mode='lines+markers', name='Actual (Oct 2025 - 2026)', line=dict(color='white', width=3)))\n",
    "\n",
    "fig_val.add_vline(x='2026-01-01', line_dash=\"dot\", line_color=\"yellow\", annotation_text=\"Test Set Start (2026)\")\n",
    "fig_val.add_hline(y=0, line_dash=\"dash\", line_color=\"red\", annotation_text=\"Zero Growth\")\n",
    "\n",
    "fig_val.update_layout(\n",
    "    title='Forecast Validation: Oct 2025 to 2026 (Historical Context + Test Set)',\n",
    "    xaxis_title='Date',\n",
    "    yaxis_title='Smoothed MoM Growth (%)',\n",
    "    template='plotly_dark',\n",
    "    hovermode=\"x unified\"\n",
    ")\n",
    "fig_val.show()\n",
    "\n",
    "# 6. Error Analysis for the 2026 Period only\n",
    "df_test_only = df_display[df_display['month'].dt.year == 2026]\n",
    "mae = np.mean(np.abs(df_test_only['actual_smoothed_growth'] - df_test_only['predicted_growth']))\n",
    "print(f\"\\n--- VALIDATION REPORT (2026 PERIOD ONLY) ---\")\n",
    "print(f\"Mean Absolute Error (MAE): {mae:.4f}%\")\n"
]

for cell in nb['cells']:
    if cell['cell_type'] == 'code' and '1.3.B Final Model Validation' in ''.join(cell['source']):
        cell['source'] = new_source
        break

with open('Data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
